#!/usr/bin/env python3
"""Generate drift-detectable detailed design from FastAPI and CloudFormation artifacts."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import shutil
import tempfile
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - environment contract
    yaml = None
try:
    import sqlglot
    from sqlglot import exp
except ImportError:  # pragma: no cover - environment contract
    sqlglot = exp = None


class DesignError(RuntimeError):
    pass


HTTP_METHODS = {"get", "put", "post", "delete", "options", "head", "patch", "trace"}


class RuntimeCallOrder(ast.NodeVisitor):
    """Collect calls in Python evaluation order rather than AST breadth order."""

    def __init__(self) -> None:
        self.calls: list[ast.Call] = []

    def visit_Call(self, node: ast.Call) -> None:
        self.visit(node.func)
        for argument in node.args:
            self.visit(argument)
        for keyword in node.keywords:
            self.visit(keyword.value)
        self.calls.append(node)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def display_call(call: ast.Call) -> str:
    parts: list[str] = []
    node: ast.AST = call.func
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    return ".".join(reversed(parts)) or "call"


def route_decorator(function: ast.FunctionDef | ast.AsyncFunctionDef) -> tuple[str, str] | None:
    for decorator in function.decorator_list:
        if not isinstance(decorator, ast.Call) or not isinstance(decorator.func, ast.Attribute):
            continue
        method = decorator.func.attr.lower()
        if method in HTTP_METHODS and decorator.args and isinstance(decorator.args[0], ast.Constant):
            return method.upper(), str(decorator.args[0].value)
    return None


def router_operations(path: Path) -> list[dict[str, Any]]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError) as exc:
        raise DesignError(f"cannot parse router {path}: {exc}") from exc
    operations: list[dict[str, Any]] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        route = route_decorator(node)
        if route is None:
            continue
        returns = [child for child in ast.walk(node) if isinstance(child, ast.Return)]
        if not node.body or not isinstance(node.body[-1], ast.Return):
            raise DesignError(f"{path}:{node.name}: route must end in a direct return")
        returned = node.body[-1].value
        if isinstance(returned, ast.Await):
            returned = returned.value
        if not isinstance(returned, ast.Call):
            raise DesignError(f"{path}:{node.name}: final return must directly call the response producer")
        if any(isinstance(ret.value, ast.Name) for ret in returns):
            raise DesignError(f"{path}:{node.name}: returning a response variable is forbidden")
        # Walk only the function body. Walking the function node also visits route
        # decorators, which are registration metadata rather than runtime calls.
        collector = RuntimeCallOrder()
        for statement in node.body:
            collector.visit(statement)
        calls = collector.calls
        operations.append({"method": route[0], "path": route[1], "function": node.name, "source": str(path), "calls": [display_call(call) for call in calls]})
    return operations


def render_sequences(operations: list[dict[str, Any]]) -> str:
    lines = ["<!-- AUTO-GENERATED by designflow.py -->", "# FastAPI operation sequences"]
    for operation in operations:
        lines += ["", f"## {operation['method']} {operation['path']} — `{operation['function']}`", "", "```mermaid", "sequenceDiagram", "    participant Client", "    participant Router"]
        lines.append(f"    Client->>Router: {operation['method']} {operation['path']}")
        for index, call in enumerate(operation["calls"], 1):
            participant = "F" + str(index)
            lines.append(f"    participant {participant} as {call}")
            lines.append(f"    Router->>{participant}: call")
            lines.append(f"    {participant}-->>Router: result")
        lines += ["    Router-->>Client: response", "```"]
    return "\n".join(lines) + "\n"


def load_structured(path: Path) -> Any:
    text = path.read_text(encoding="utf-8")
    if path.suffix.lower() == ".json":
        return json.loads(text)
    if yaml is None:
        raise DesignError("PyYAML is required for YAML input")

    class Loader(yaml.SafeLoader):
        pass

    def unknown(loader: Any, tag_suffix: str, node: Any) -> Any:
        if isinstance(node, yaml.ScalarNode):
            return {"tag": tag_suffix, "value": loader.construct_scalar(node)}
        if isinstance(node, yaml.SequenceNode):
            return {"tag": tag_suffix, "value": loader.construct_sequence(node)}
        return {"tag": tag_suffix, "value": loader.construct_mapping(node)}

    Loader.add_multi_constructor("!", unknown)
    return yaml.load(text, Loader=Loader)


def ref_name(value: Any) -> str:
    if isinstance(value, dict) and "$ref" in value:
        return str(value["$ref"]).rsplit("/", 1)[-1]
    if isinstance(value, dict):
        return str(value.get("type") or value.get("content") or "inline")
    return "-"


def openapi_docs(document: dict[str, Any]) -> tuple[str, str]:
    operations: list[tuple[str, str, dict[str, Any]]] = []
    seen: set[str] = set()
    for path, item in sorted(document.get("paths", {}).items()):
        for method, operation in sorted(item.items()):
            if method.lower() not in HTTP_METHODS or not isinstance(operation, dict):
                continue
            operation_id = operation.get("operationId") or f"{method}-{path}"
            if operation_id in seen:
                raise DesignError(f"duplicate OpenAPI operationId: {operation_id}")
            seen.add(operation_id)
            operations.append((method.upper(), path, operation))
    catalog = ["<!-- AUTO-GENERATED by designflow.py -->", "# API catalog", "", "| Method | Path | Operation ID | Summary | Requirement IDs |", "|---|---|---|---|---|"]
    interfaces = ["<!-- AUTO-GENERATED by designflow.py -->", "# API interfaces"]
    for method, path, operation in operations:
        requirements = operation.get("x-requirement-ids", [])
        catalog.append(f"| {method} | `{path}` | `{operation.get('operationId', '-')}` | {operation.get('summary', '-')} | {', '.join(requirements) or '-'} |")
        request = operation.get("requestBody", {}).get("content", {})
        request_types = [f"{media}:{ref_name(body.get('schema', {}))}" for media, body in sorted(request.items())]
        responses = []
        for status, response in sorted(operation.get("responses", {}).items()):
            schemas = [f"{media}:{ref_name(body.get('schema', {}))}" for media, body in sorted(response.get("content", {}).items())]
            responses.append(f"{status}={'/'.join(schemas) or response.get('description', '-')}" )
        interfaces += ["", f"## {method} {path}", "", f"- Request: {', '.join(request_types) or '-'}", f"- Responses: {', '.join(responses) or '-'}"]
    schemas = document.get("components", {}).get("schemas", {})
    interfaces += ["", "## Schemas", "", "| Name | Required fields | Properties |", "|---|---|---|"]
    for name, schema in sorted(schemas.items()):
        properties = [f"{key}:{value.get('type', ref_name(value))}" for key, value in sorted(schema.get("properties", {}).items())]
        interfaces.append(f"| `{name}` | {', '.join(schema.get('required', [])) or '-'} | {', '.join(properties) or '-'} |")
    return "\n".join(catalog) + "\n", "\n".join(interfaces) + "\n"


def sql_docs(root: Path) -> tuple[str, str]:
    if sqlglot is None or exp is None:
        raise DesignError("SQLGlot is required for SQL AST analysis")
    queries: list[dict[str, Any]] = []
    matrix: dict[str, set[str]] = defaultdict(set)
    for path in sorted(root.rglob("*.sql")):
        try:
            statements = sqlglot.parse(path.read_text(encoding="utf-8"))
        except Exception as exc:
            raise DesignError(f"cannot parse SQL {path}: {exc}") from exc
        for index, statement in enumerate(statements, 1):
            tables = {table.name for table in statement.find_all(exp.Table)}
            target = None
            if isinstance(statement, (exp.Insert, exp.Update, exp.Delete)):
                target_table = statement.this if isinstance(statement.this, exp.Table) else statement.this.find(exp.Table)
                target = target_table.name if isinstance(target_table, exp.Table) else None
            operation = "SELECT"
            letter = "R"
            if isinstance(statement, exp.Insert):
                operation, letter = "INSERT", "C"
            elif isinstance(statement, exp.Update):
                operation, letter = "UPDATE", "U"
            elif isinstance(statement, exp.Delete):
                operation, letter = "DELETE", "D"
            for table in tables:
                matrix[table].add(letter if table == target else "R")
            relative = path.relative_to(root).with_suffix("").as_posix().replace("/", "-")
            queries.append({"id": f"{relative}-{index}", "file": str(path), "operation": operation, "target": target or "-", "tables": sorted(tables)})
    query_lines = ["<!-- AUTO-GENERATED by designflow.py -->", "# Query objects", "", "| Query | File | Operation | Target | Tables |", "|---|---|---|---|---|"]
    for query in queries:
        query_lines.append(f"| `{query['id']}` | `{query['file']}` | {query['operation']} | {query['target']} | {', '.join(query['tables']) or '-'} |")
    crud = ["<!-- AUTO-GENERATED by designflow.py -->", "# CRUD matrix", "", "| Table | C | R | U | D |", "|---|:---:|:---:|:---:|:---:|"]
    for table, letters in sorted(matrix.items()):
        crud.append("| " + table + " | " + " | ".join(letter if letter in letters else "-" for letter in "CRUD") + " |")
    return "\n".join(crud) + "\n", "\n".join(query_lines) + "\n"


def cfn_docs(template: dict[str, Any]) -> tuple[str, str]:
    resources = ["<!-- AUTO-GENERATED by designflow.py -->", "# CloudFormation resources", "", "| Logical ID | Type | Condition | DependsOn |", "|---|---|---|---|"]
    for logical_id, resource in sorted(template.get("Resources", {}).items()):
        depends = resource.get("DependsOn", "-")
        if isinstance(depends, list):
            depends = ", ".join(depends)
        resources.append(f"| `{logical_id}` | `{resource.get('Type', '-')}` | {resource.get('Condition', '-')} | {depends} |")
    parameters = ["<!-- AUTO-GENERATED by designflow.py -->", "# CloudFormation parameters", "", "| Name | Type | Default | Allowed values | Description |", "|---|---|---|---|---|"]
    for name, parameter in sorted(template.get("Parameters", {}).items()):
        allowed = parameter.get("AllowedValues", "-")
        if isinstance(allowed, list):
            allowed = ", ".join(map(str, allowed))
        parameters.append(f"| `{name}` | `{parameter.get('Type', '-')}` | {parameter.get('Default', '-')} | {allowed} | {parameter.get('Description', '-')} |")
    return "\n".join(resources) + "\n", "\n".join(parameters) + "\n"


def write_bundle(out: Path, files: dict[str, str], sources: list[Path]) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=out.name + ".", dir=out.parent))
    try:
        manifest = {"schema_version": 1, "sources": [{"path": str(path), "sha256": sha(path)} for path in sorted(set(sources))], "generated": sorted(files)}
        for name, content in files.items():
            (temporary / name).write_text(content, encoding="utf-8", newline="\n")
        (temporary / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        if out.exists():
            shutil.rmtree(out)
        os.replace(temporary, out)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)


def compare_bundle(expected: Path, actual: Path) -> None:
    expected_files = {path.relative_to(expected) for path in expected.rglob("*") if path.is_file()}
    actual_files = {path.relative_to(actual) for path in actual.rglob("*") if path.is_file()}
    if expected_files != actual_files:
        raise DesignError(f"generated file set drift: expected={sorted(map(str, expected_files))} actual={sorted(map(str, actual_files))}")
    for relative in expected_files:
        if (expected / relative).read_bytes() != (actual / relative).read_bytes():
            raise DesignError(f"generated design drift: {actual / relative}")


def generate_fastapi(args: argparse.Namespace, out: Path) -> None:
    routers = sorted(args.source_root.rglob("router.py"))
    if not routers:
        raise DesignError("no router.py found")
    function_files = sorted({path.with_name("functions.py") for path in routers})
    missing = [path for path in function_files if not path.is_file()]
    if missing:
        raise DesignError("each router.py requires a sibling functions.py: " + ", ".join(map(str, missing)))
    operations = [operation for path in routers for operation in router_operations(path)]
    openapi = load_structured(args.openapi)
    api, interfaces = openapi_docs(openapi)
    crud, queries = sql_docs(args.sql_root)
    sources = routers + function_files + [args.openapi] + sorted(args.sql_root.rglob("*.sql"))
    write_bundle(out, {"SEQUENCES.md": render_sequences(operations), "API_CATALOG.md": api, "INTERFACES.md": interfaces, "CRUD.md": crud, "QUERY_OBJECTS.md": queries}, sources)


def generate_cdk(args: argparse.Namespace, out: Path) -> None:
    resources, parameters = cfn_docs(load_structured(args.template))
    write_bundle(out, {"RESOURCES.md": resources, "PARAMETERS.md": parameters}, [args.template])


def build_parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    sub = root.add_subparsers(dest="kind", required=True)
    fastapi = sub.add_parser("fastapi")
    fastapi.add_argument("--source-root", required=True, type=Path)
    fastapi.add_argument("--openapi", required=True, type=Path)
    fastapi.add_argument("--sql-root", required=True, type=Path)
    fastapi.add_argument("--out", required=True, type=Path)
    fastapi.add_argument("--check", action="store_true")
    cdk = sub.add_parser("cdk")
    cdk.add_argument("--template", required=True, type=Path)
    cdk.add_argument("--out", required=True, type=Path)
    cdk.add_argument("--check", action="store_true")
    return root


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.check:
            with tempfile.TemporaryDirectory() as directory:
                candidate = Path(directory) / "generated"
                (generate_fastapi if args.kind == "fastapi" else generate_cdk)(args, candidate)
                compare_bundle(candidate, args.out)
            print(f"generated design current: {args.out}")
        else:
            (generate_fastapi if args.kind == "fastapi" else generate_cdk)(args, args.out)
            print(f"generated design: {args.out}")
        return 0
    except (DesignError, OSError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
