#!/usr/bin/env python3
"""Validate, render, and enforce freshness of official standards sources."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from datetime import date, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


class StandardsError(RuntimeError):
    pass


REQUIRED = {"id", "authority", "title", "version", "url", "checked_at", "refresh_days", "profiles"}
OFFICIAL_HOST_SUFFIXES = ("computer.org", "amazon.com", "amazonaws.com", "microsoft.com", "google.com", "googleapis.com", "oracle.com")


def load(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise StandardsError(f"cannot read registry: {exc}") from exc
    if not isinstance(value, dict) or set(value) != {"schema_version", "sources"} or value["schema_version"] != 1 or not isinstance(value["sources"], list):
        raise StandardsError("invalid standards registry envelope")
    seen: set[str] = set()
    for source in value["sources"]:
        if not isinstance(source, dict) or set(source) != REQUIRED:
            raise StandardsError("invalid standards source fields")
        if source["id"] in seen:
            raise StandardsError(f"duplicate source ID: {source['id']}")
        seen.add(source["id"])
        if any(not isinstance(source[key], str) or not source[key].strip() for key in ["id", "authority", "title", "version"]):
            raise StandardsError(f"{source['id']}: blank metadata")
        parsed = urlparse(source["url"])
        if parsed.scheme != "https" or not any(parsed.hostname == suffix or str(parsed.hostname).endswith("." + suffix) for suffix in OFFICIAL_HOST_SUFFIXES):
            raise StandardsError(f"{source['id']}: URL is not an allowed official HTTPS host")
        try:
            date.fromisoformat(source["checked_at"])
        except (TypeError, ValueError) as exc:
            raise StandardsError(f"{source['id']}: checked_at must be ISO date") from exc
        if not isinstance(source["refresh_days"], int) or source["refresh_days"] < 1:
            raise StandardsError(f"{source['id']}: refresh_days must be positive")
        if not isinstance(source["profiles"], list) or not source["profiles"] or len(source["profiles"]) != len(set(source["profiles"])):
            raise StandardsError(f"{source['id']}: profiles must be a unique non-empty list")
    return value


def freshness(registry: dict[str, Any], as_of: date) -> None:
    stale = []
    for source in registry["sources"]:
        expires = date.fromisoformat(source["checked_at"]) + timedelta(days=source["refresh_days"])
        if as_of > expires:
            stale.append(f"{source['id']} expired {expires.isoformat()}")
    if stale:
        raise StandardsError("stale official-source verification: " + "; ".join(stale))


def render(registry: dict[str, Any]) -> str:
    lines = [
        "<!-- AUTO-GENERATED by standardsflow.py; edit governance/standards/registry.json instead. -->",
        "# Engineering standards sources",
        "",
        "| ID | Authority | Source | Version | Checked | Refresh days | Profiles |",
        "|---|---|---|---|---|---:|---|",
    ]
    for source in registry["sources"]:
        lines.append(f"| `{source['id']}` | {source['authority']} | [{source['title']}]({source['url']}) | {source['version']} | {source['checked_at']} | {source['refresh_days']} | {', '.join(source['profiles'])} |")
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    root.add_argument("command", choices=["validate", "generate", "check"])
    root.add_argument("--registry", type=Path, default=Path("governance/standards/registry.json"))
    root.add_argument("--out", type=Path, default=Path("docs/standards/SOURCES.md"))
    root.add_argument("--as-of", type=date.fromisoformat, default=date.today())
    return root


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        registry = load(args.registry)
        freshness(registry, args.as_of)
        if args.command == "generate":
            atomic_write(args.out, render(registry))
            print(f"generated {args.out}")
        elif args.command == "check":
            if not args.out.is_file() or args.out.read_text(encoding="utf-8") != render(registry):
                raise StandardsError(f"generated standards docs drift: {args.out}")
            print(f"standards current and fresh: {len(registry['sources'])} sources")
        else:
            print(f"standards valid and fresh: {len(registry['sources'])} sources")
        return 0
    except StandardsError as exc:
        print(f"ERROR: {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
